---
- name: Remove curl-minimal if present (RHEL)
  when: ansible_os_family == "RedHat"
  ansible.builtin.package:
    name: curl-minimal
    state: absent

- name: Ensure required packages are installed
  ansible.builtin.package:
    name:
      - git
      - curl
    state: present

- name: Add Node source repo (RHEL)
  when: ansible_os_family == "RedHat"
  ansible.builtin.shell: |
    curl -fsSL https://rpm.nodesource.com/setup_22.x | bash -
  args:
    executable: /bin/bash

- name: Add Node source repo (Debian)
  when: ansible_os_family == "Debian"
  ansible.builtin.shell: |
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
  args:
    executable: /bin/bash

- name: Install Node.js
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Clone the quiz-ansible repo
  ansible.builtin.git:
    repo: https://github.com/franklin-tutorials/quiz-ansible.git
    dest: /opt/quiz-ansible
    version: main

- name: Install dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /opt/quiz-ansible

- name: Build the app
  ansible.builtin.command: npm run build
  args:
    chdir: /opt/quiz-ansible

- name: Install serve globally
  command: npm install -g serve

- name: Serve the app
  ansible.builtin.command: serve -s dist
  args:
    chdir: /opt/quiz-ansible
  async: 3600
  poll: 0

